networks:
  proxy_primary-network:
    external: true
  proxy_sql-network:
    external: true

services:
  soundpanel-service:
    image: php:8.3-fpm
    container_name: soundpanel
    hostname: soundpanel
    volumes:
      - /src/soundpanel/web:/var/www/html/soundpanel
      - /src/soundpanel/www.conf:/usr/local/php-fpm.d/www.conf
      - /var/log:/var/log
    networks:
      - proxy_sql-network
      - proxy_primary-network
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
